apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-crud-apis
spec:
  selector:
    matchLabels:
      app: golang-crud-apis
  replicas: 2
  template:
    metadata:
      labels:
        app: golang-crud-apis
    spec:
      containers:
        - name: golang-crud-apis
          image: sridharaprasadhosahalli/golang-crud-apis:latest
          imagePullPolicy: IfNotPresent

