apiVersion: v1
kind: Pod
metadata:
  name: golang-crud-api
  labels:
    run: golang-crud-api
spec:
  containers:
  - name: golang-crud-api
    image: sridharaprasadhosahalli/golang-crud-apis:latest
    ports:
    - containerPort: 8080